# Generated by Django 5.2.17 on 2026-09-30 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0016_engineconfig_serverstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('games', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('LL', models.IntegerField(default=0)),
                ('LD', models.IntegerField(default=0)),
                ('DD', models.IntegerField(default=0)),
                ('DW', models.IntegerField(default=0)),
                ('WW', models.IntegerField(default=0)),
                ('llr', models.FloatField(default=0.0)),
                ('test', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='OpenBench.test')),
            ],
            options={
                'indexes': [models.Index(fields=['test', 'created'], name='snapshot_test_created')],
            },
        ),
    ]
