# Generated by Django 5.2.17 on 2026-10-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0019_machine_host_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('state', models.JSONField(default=dict)),
                ('games', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('analysed_bytes', models.BigIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_analysis', to='OpenBench.test')),
            ],
        ),
    ]
