# Generated by Django 5.2.17 on 2026-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0021_game_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=64, unique=True)),
                ('tag', models.CharField(blank=True, max_length=128)),
                ('sha', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('default_branch', models.CharField(blank=True, max_length=128)),
                ('pinned', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBranchCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=64)),
                ('sha', models.CharField(max_length=64)),
                ('on_default_branch', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('checks', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('engine', 'sha'), name='default_branch_commit')],
            },
        ),
    ]
