"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

def env_flag(name):
    return os.environ.get(name, '').strip().lower() in ('1', 'true', 'yes')

def env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Production is the default. See docs/DEPLOYMENT.md for every OPENBENCH_* variable
DEBUG = env_flag('OPENBENCH_DEBUG')

SECRET_KEY = os.environ.get('OPENBENCH_SECRET_KEY') or (get_random_secret_key() if DEBUG else None)
if not SECRET_KEY:
    raise ImproperlyConfigured('OPENBENCH_SECRET_KEY must be set unless OPENBENCH_DEBUG is enabled')

ALLOWED_HOSTS        = env_list('OPENBENCH_ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = ['https://%s' % (host) for host in ALLOWED_HOSTS if not host.startswith('.')]

if env_flag('OPENBENCH_BEHIND_TLS_PROXY'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

DATA_DIR   = os.environ.get('OPENBENCH_DATA_DIR', BASE_DIR)
MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'Media')

INSTALLED_APPS = [
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
